configuration:
  provider: aws
  backupStorageLocation:
    name: default
    bucket: <YOUR_BACKUP_BUCKET>
    config:
      region: us-east-1
      s3ForcePathStyle: true
      s3Url: https://s3.amazonaws.com
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=<YOUR_AWS_ACCESS_KEY>
      aws_secret_access_key=<YOUR_AWS_SECRET_KEY>
