apiVersion: gcp.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: demo-gke-cluster
spec:
  id: demo-gke
  parameters:
    location: us-central1
    version: "1.29"
    nodeCount: 2
    nodeSize: e2-medium
